### ISSUE TITLE
ActorModel

### ISSUE THREAD

**Issue by Arczi89** [SebastanBucki07/sebaQuiz#46]
Może warto tutaj rozważyć tablicę zamiast numerować kolejne zmienne actor1, actor2 itp

export interface ActorModel{
  "id": number,
  "title": string,
  "actor1":string,
  "actor2": string,
  "actor3": string,
  "actor4": string,
  "actor5": string,
  "actor6": string,
  "actor7": string,
  "actor8": string,
  "actor9": string,
}

export interface ActorModel {
  "id": number,
  "title": string,
  "actors": string[],
}

uniknie się też takich wywołań wtedy:

![image](https://user-images.githubusercontent.com/30185821/229011591-c4702c17-cbe7-46ce-b223-af8f013d76a0.png)

**Comment by SebastanBucki07** [comment]
Resolved in https://github.com/SebastanBucki07/sebaQuiz/pull/65
